<?php

/**
 * Модуль должен располагаться на хосте, на котором находится база данных.
 * Поскольку конфигурации таблиц различны, то и модуль формирующий .json для каждого хоста - индивидуальный.
 * Path: /htdocs/sites/admissions.sfu-kras.ru/modules/sfu_data_getter
 */

/**
 * Implements hook_menu.
 */
function sfu_data_getter_menu()
{
    $items = array();
    $items[] = array(
        'path' => 'get-admissions',
        'callback' => '_page',
        'access' => user_access('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * Page.
 */
function _page()
{
    // тип страницы .json
    header("Content-type: application/json");
    // CORS
    header("Access-Control-Allow-Origin: https://next.sfu-kras.ru");

    // Получение материалов, имеющих самую свежую ревизию за исключением тех, которые указаны явно
    $q1 = "SELECT node_revisions.nid, MAX(node_revisions.vid) AS vid, node_revisions.title, node_revisions.body, node_revisions.timestamp, node.status
           FROM node_revisions
           JOIN node
           ON node.nid = node_revisions.nid
           WHERE node.status = 1
           AND node.nid NOT IN (1629, 1627)
           GROUP BY node_revisions.nid";
    $r1 = db_query($q1);

    // сборка массива со всеми новостями	
    while ($e = db_fetch_object($r1)) {

        // Подготовка значений
        $name = $e->title;
        $name = strip_tags($name);
        $name = trim($name);

        $nid = $e->nid;

        $text = $e->body;
        $text = strip_tags($text);
        $text = trim($text);

        $timestamp = $e->timestamp;

        // Сборка массива
        $j1[] = array(
            'name'          => $name,
            'link'          => "https://admissions.sfu-kras.ru/node/$nid",
            'text'          => $text,
            'timestamp'     => $timestamp,
            // 'type' => $e->type,
            // 'created'   => $e->created,
            // 'changed'   => $e->changed,
        );
    }

    // Отладка
    // echo '<pre>';
    // print_r($j1);
    // echo '</pre>';

    echo json_encode($j1);
}
