<?php

/**
 * Модуль должен располагаться на хосте, на котором находится база данных.
 * Поскольку конфигурации таблиц различны, то и модуль формирующий .json для каждого хоста - индивидуальный.
 * Path: /htdocs/sites/about.sfu-kras.ru/modules/sfu_data_getter
 */

/**
 * Implements hook_menu.
 */
function sfu_data_getter_menu()
{
    $items = array();
    $items[] = array(
        'path' => 'get-about',
        'callback' => '_page',
        'access' => user_access('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * Page.
 */
function _page()
{
    // тип страницы .json
    header("Content-type: application/json");
    // CORS
    header("Access-Control-Allow-Origin: https://next.sfu-kras.ru");

    // получение всех объявлений
    $q1 = "SELECT nid, title, type, created, changed FROM node WHERE status = 1";
    $r1 = db_query($q1);

    // сборка массива со всеми новостями	
    while ($e = db_fetch_object($r1)) {

        $j1[] = array(
            'name'      => $e->title,
            'link'      => 'https://about.sfu-kras.ru/node/' . $e->nid,
            'type'      => $e->type,
            'created'   => $e->created,
            'changed'   => $e->changed,
        );
    }

    // echo '<pre>';
    // print_r($j1);
    // echo '</pre>';

    echo json_encode($j1);
}
