<?php

/**
 * Implements hook menu.
 * 
 * ! Модуль должен располагаться на хосте, на котором находится база данных.
 * ! Поскольку конфигурации баз данных различны, то и модуль формирующий .json для каждого раздела будет индивидуальный.
 * ! Размещается: /htdocs/modules/sfu__data_getter
 * ! Вариация модуля под Drupal 5
 */

/** 
 * Implementation of hook_menu().
 * https://drupalbook.org/ru/drupal/hookmenu-drupal-sozdanie-stranic-cherez-modul
 * https://api.drupal.org/api/drupal/developer%21hooks%21core.php/function/hook_menu/5.x
 */



function sfu_data_getter_menu()
{
    $items = array();
    $items[] = array(
        'path' => 'get-sfu',
        'callback' => '_page',
        'access' => user_access('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}


function _page()
{
    // тип страницы .json
    header("Content-type: application/json");
    // CORS
    header("Access-Control-Allow-Origin: https://next.sfu-kras.ru");

    // получение всех объявлений
    $q1 = "SELECT nid, title FROM node WHERE status = 1";
    $r1 = db_query($q1);

    // сборка массива со всеми новостями	
    while ($e = db_fetch_object($r1)) {

        $j1[] = array(
            'name' => $e->title,
            'link' => 'https://www.sfu-kras.ru/node/' . $e->nid,
            'type' => $e->type,
        );
    }

    // echo '<pre>';
    // print_r($j1);
    // echo '</pre>';

    echo json_encode($j1);
}
